# Generated by Django 3.2 on 2022-01-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
