# Generated by Django 3.2 on 2022-01-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookinstance_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='file',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
